### ISSUE TITLE
Version 2.2 Statistics

### ISSUE THREAD

**Issue by sgroom-lb** [scamfield/telegraf-bind9#1]
Unable to determine why v2.2 stats are not parsing. I'm no python expert but it seems everything you're parsing for exists when I pull the raw output from the bind 9 statistics channel. 

I've tried it on the following versions:

BIND 9.11.3-1ubuntu1.9-Ubuntu
BIND 9.9.5-9+deb8u18-Debian
<?xml version="1.0" encoding="UTF-8"?>
--
  | <?xml-stylesheet type="text/xsl" href="/bind9.xsl"?>
  | <isc version="1.0">
  | <bind>
  | <statistics version="2.2">
  | <views>
  | <view>
  | <name>_default</name>
  | <zones>

Output from  bind9_metrics.py is identical for both versions. 
{"views": {}, "server": {}, "memory": {}, "cache": {}, "counter": {}, "socketcounter": {}, "zonemaintenancecounter": {}, "resolvercounter": {}, "incounter": {}, "outcounter": {}}

xml output attached

[bind9-8053_xml.txt](https://github.com/scamfield/telegraf-bind9/files/3734550/bind9-8053_xml.txt)

**Comment by sgroom-lb** [comment]
Ok, it seems those versions return as xml v1... that explains the problem.

**Comment by scamfield** [comment]
User discoverd the problem.
